# general params
--trajectory:
  - ../local_search/trajectories/303_5ns_trajectory.pdb
--time-limit:
  - 0.05
--omp-threads:
  - 0
--repetitions:
  - 2
# local search specific params
--jump-chance:
  - 0.1
--random-frame-chance:
  - 0.01
--memory-size:
  - 0
# not affecting results other params
--write-as-csv: true
--random-seed: true
--matrix-size: -1
--show-logs: false
--show-rmsd-counter: false
--show-current-best: false
--show-route-best: false
